http:
  ip: 0.0.0.0
  port: 8080
  # debug、release
  mode: debug
redis:
  host: "192.168.239.161"
  port: 6379
  pwd: "123456"
mysql:
  dsn: "root:123456@tcp(192.168.239.161:3306)/mediahub?collation=utf8mb4_unicode_ci&charset=utf8mb4"
  maxLifeTime: 3600
  maxOpenConn: 10
  maxIdleConn: 10
log:
  # panic,fatal,error,warn,warning,info,debug,trace
  level: "info"
  logPath: "runtime/logs/app.log"
cos:

dependOn:
  shortUrl:
    address: "2410-shorturl:50051"
    accessToken: "4cdQRSk678lTe015hpqWXYZAab2VrwxyGHIJKjmn"
  user:
    address: "http://192.168.239.161:8082"
