server:
  ip: 127.0.0.1
  port: 50051
  accessToken: "me256487diahubdev122sapguumyqcang1cozholoud"
redis:
  host: "127.0.0.1"
  port: 6379
  pwd: ""
mysql:
  dsn: "root:root@tcp(127.0.0.1:3306)/mediahub?collation=utf8mb4_unicode_ci&charset=utf8mb4"
  maxLifeTime: 3600
  maxOpenConn: 10
  maxIdleConn: 10
log:
  # panic,fatal,error,warn,warning,info,debug,trace
  level: "info"
  logPath: "runtime/logs/app.log"
shortDomain: "http://localhost:8081/p/"
userShortDomain: "http://localhost:8081/u/"
